config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :properties do
    resources :bookings, only: %i[new create]
  end

  get 'my_properties', to: 'properties#my_properties', as: :my_properties

  resources :bookings, except: %i[new create]
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  # Associations
  belongs_to :user
  belongs_to :property

  # Validations
  validates :start_date, :end_date, presence: true

  # Virtual Attribute
  attr_accessor :date_range

  def separate_dates
    dates = date_range.split(" to ")
    self.start_date = Date.strptime(dates[0], "%d/%m/%Y")
    self.end_date = Date.strptime(dates[1], "%d/%m/%Y")
  end

  def total_days
    (end_date - start_date).to_i
  end
end

app/models/country.rb
class Country < ApplicationRecord
  # Associations
  has_many :properties, dependent: :destroy

  # Validations
  validates :name, uniqueness: true
end

app/models/property.rb
class Property < ApplicationRecord
  # Associations
  belongs_to :user
  belongs_to :country
  has_many :bookings
  has_many_attached :photos

  # Validations
  validates :name,
            :address,
            :start_date,
            :end_date,
            :property_type,
            :bedroom_count,
            :bed_count,
            presence: true

  # Enums
  enum property_type: {
    entire_place: 0,
    room_only: 1
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Associations
  has_many :properties, dependent: :destroy
  has_one_attached :photo

  # Validations
  validates :first_name, :last_name, :user_type, presence: true

  # Enums
  enum user_type: {
    landlord: 0,
    guest: 1
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  include Pundit::Authorization

  # Pundit: allow-list approach
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def user_not_authorized
    flash[:alert] = I18n.t("pundit.user_not_authorized")
    redirect_to(root_path)
  end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name
                                                         user_type date_of_birth
                                                         about photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name
                                                                user_type date_of_birth
                                                                about photo])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_property, only: %i[new create]
  before_action :set_booking, only: %i[edit update show destroy]

  def index
    @bookings = policy_scope(Booking).where(user: current_user)
  end

  def show; end

  def new
    @booking = Booking.new

    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.property = @property
    @booking.user = current_user
    @booking.separate_dates
    @booking.total_price = @booking.total_days * @property.price_per_night

    authorize @booking

    if @booking.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @booking.destroy

    respond_to do |format|
      format.html { redirect_to bookings_path }
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:date_range)
  end

  def set_booking
    @booking = Booking.find(params[:id])

    authorize @booking
  end

  def set_property
    @property = Property.find(params[:property_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: %i[edit update show destroy]

  def index
    @properties = policy_scope(Property)
  end

  def my_properties
    @properties = Property.where(user: current_user)

    authorize @properties
  end

  def show
    @booking = Booking.new
    @disabled_dates = @property.bookings.map { |b| (b.start_date..b.end_date).to_a }.flatten
  end

  def new
    @property = Property.new
    @countries = Country.all

    authorize @property
  end

  def create
    @property = Property.new(property_params)
    @property.user = current_user

    authorize @property

    if @property.save
      @property.user.landlord!

      redirect_to @property
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @countries = Country.all
  end

  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @property.destroy

    respond_to do |format|
      format.html { redirect_to properties_path }
    end
  end

  private

  def property_params
    params.require(:property).permit(:name, :description, :address, :start_date, :end_date,
                                     :property_type, :bed_count, :bedroom_count, :smoking, :pet,
                                     :wifi, :minimum_stay, :maximum_guests, :country_id, :price_per_night,
                                     :fee_price, :children, :elevator, :smoke_detector, :parking, :check_in,
                                     :check_out, photos: [])
  end

  def set_property
    @property = Property.find(params[:id])

    authorize @property
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])

    authorize @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="cards">
  <% @bookings.each do |booking| %>
    <%= link_to property_path(booking.property) do %>
      <div class="card-property">
        <% if booking.property.photos.attached? %>
          <%= cl_image_tag booking.property.photos.first.key %>
        <% else %>
          <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" />
        <% end %>
        <div class="card-property-infos">
          <div>
            <h2><%= booking.property.name %></h2>
            <p><%= booking.property.description %></p>
          </div>
          <h2 class="card-property-pricing">£99.99</h2>

          <% if booking.property.user.photo.attached? %>
            <%= cl_image_tag booking.property.user.photo.key, class: 'card-property-user avatar-bordered' %>
          <% else %>
            <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-property-user avatar-bordered" />
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chezmoi</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%# <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script> %>
    <link rel="stylesheet" href="https://ga.jspm.io/npm:flatpickr@4.6.9/dist/flatpickr.min.css">
  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <div class="banner w-100" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1514580597161-eb1c0b1a7971?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8cGFyaXMlMjB3aW5kb3d8ZW58MHx8MHx8fDA%3D);">
        <div class="container d-flex flex-column justify-content-center align-items-center">
          <h1><%= t('titles.home.banner') %></h1>
          <div class="buttons-home">
            <%= link_to t('buttons.properties.search'), properties_path, class: 'btn btn-home-add' %>
            <%= link_to t('buttons.properties.add'), new_property_path, class: 'btn btn-home-search' %>
          </div>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <div class="banner w-100" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.france.fr/zeaejvyq9bhj/6DEBYvt4thSw1M8I9lmzvq/d1fb4e634126fa26c338999ac1880555/AdobeStock_227511347_v1.jpg?w=1120&h=490&q=70&fl=progressive&fit=fill);">
        <div class="container d-flex flex-column justify-content-center align-items-center">
          <h1><%= t('titles.home.banner') %></h1>
          <div class="buttons-home">
            <%= link_to t('buttons.properties.search'), properties_path, class: 'btn btn-home-add' %>
            <%= link_to t('buttons.properties.add'), new_property_path, class: 'btn btn-home-search' %>
          </div>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <div class="banner w-100" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://www.civitatis.com/f/brasil/brasilia/brasilia.jpg);">
        <div class="container d-flex flex-column justify-content-center align-items-center">
          <h1><%= t('titles.home.banner') %></h1>
          <div  class="buttons-home">
            <%= link_to t('buttons.properties.search'), properties_path, class: 'btn btn-home-add' %>
            <%= link_to t('buttons.properties.add'), new_property_path, class: 'btn btn-home-search' %>
          </div>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</div>

<div class="mb-5">
  <h1 class='text-center my-3'><strong><%= t('titles.home.subtitle') %></strong></h1>
  <div class='d-flex justify-content-around'>
    <div class='home-card'>
      <%= image_tag 'paris.jpg', class: 'city-image' %>
      <div class='card-info'>
        <h3><%= t('countries.paris') %></h3>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla reiciendis numquam ad beatae omnis nostrum illo iure sapiente porro cupiditate perspiciatis culpa pariatur aperiam vel quam reprehenderit quo, ea delectus.</p>
      </div>
    </div>

    <div class='home-card'>
      <%= image_tag 'brasilia.jpg', class: 'city-image' %>
      <div class='card-info'>
        <h3><%= t('countries.brasilia') %></h3>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla reiciendis numquam ad beatae omnis nostrum illo iure sapiente porro cupiditate perspiciatis culpa pariatur aperiam vel quam reprehenderit quo, ea delectus.</p>
      </div>
    </div>
  </div>
</div>

app/views/properties/_form.html.erb
<%= simple_form_for(@property) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs p-5">
    <%= f.input :name,
                required: true,
                autofocus: true %>
    <%= f.association :country,
                      collection: @countries,
                      include_blank: true %>
    <%= f.input :description, as: :text %>
    <%= f.input :start_date %>
    <%= f.input :end_date %>
    <%= f.input :check_in %>
    <%= f.input :check_out %>
    <%= f.input :address %>
    <%= f.input :bedroom_count %>
    <%= f.input :bed_count %>
    <%= f.input :smoking %>
    <%= f.input :pet %>
    <%= f.input :wifi %>
    <%= f.input :children %>
    <%= f.input :elevator %>
    <%= f.input :smoke_detector %>
    <%= f.input :parking %>
    <%= f.input :minimum_stay %>
    <%= f.input :maximum_guests %>
    <%= f.input :price_per_night %>
    <%= f.input :fee_price %>
    <%= f.input :property_type, collection: Property.property_types.keys.map { |k| [t("activerecord.attributes.property.property_types.#{k}"), k]} %>
     <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  </div>

  <div class="form-actions text-center">
    <%= f.button :submit, t('helpers.submit.property.create') %>
  </div>
<% end %>

app/views/properties/_properties_cards.html.erb
<div class="cards">
  <% properties.each do |property| %>
    <%= link_to property_path(property) do %>
      <div class="card-property">
        <% if property.photos.attached? %>
          <%= cl_image_tag property.photos.first.key %>
        <% else %>
          <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" />
        <% end %>
        <div class="card-property-infos">
          <div>
            <h2><%= property.name %></h2>
            <p><%= property.description %></p>
          </div>
          <h2 class="card-property-pricing">£99.99</h2>

          <% if property.user.photo.attached? %>
            <%= cl_image_tag property.user.photo.key, class: 'card-property-user avatar-bordered' %>
          <% else %>
            <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-property-user avatar-bordered" />
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/properties/_property.html.erb
<%= turbo_frame_tag 'property' do %>
  <div class="">
    <div class="">
      <div><%= property.name %></div>
    </div>
  </div>
<% end %>

app/views/properties/index.html.erb
<%# <h1><%= t('titles.property.list') %>
<div class="m-4">
  <h1>Barra de Busca Aqui</h1>

  <%= render 'properties_cards', properties: @properties %>
</div>

app/views/properties/my_properties.html.erb
<%= render 'properties_cards', properties: @properties %>

app/views/properties/new.html.erb
<%= render 'form' %>

app/views/properties/show.html.erb
<div class="d-flex">
  <div class="image-property">
    <% if @property.photos.attached? %>
      <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
          <% @property.photos.each_with_index do |photo, index| %>
            <div class="carousel-item <%= "active" if index.zero? %>"">
              <%= cl_image_tag photo.key, class: 'd-block w-100', crop: :fit %>
            </div>
          <% end %>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
    <% end %>
  </div>

  <div class="property-info">
    <h1 class="text-center mb-4"><%= @property.name %></h1>
    <p><%= @property.description %></p>

    <div class="information-grid">
      <p><strong><%= t('titles.property.location') %>:</strong></p>
      <p class="text-center"><%= @property.address %></p>
      <p><strong><%= t('activerecord.attributes.property.bed_count') %>:</strong></p>
      <p class="text-center"><%= @property.bed_count %> camas</p>
      <p><strong><%= t('activerecord.attributes.property.bedroom_count') %>:</strong></p>
      <p class="text-center"><%= @property.bedroom_count %> quartos</p>
      <p><strong><%= t('activerecord.attributes.property.maximum_guests') %>:</strong></p>
      <p class="text-center"><%= @property.maximum_guests %> passoas</p>
      <p><strong><%= t('activerecord.attributes.property.minimum_stay') %>:</strong></p>
      <p class="text-center"><%= @property.minimum_stay %> dias</p>
      <p><strong><%= t('activerecord.attributes.property.pet') %>:</strong></p>
      <p class="text-center"><%= @property.pet ? '<i class="fa-solid fa-paw permited"></i>'.html_safe : '<i class="fa-solid fa-ban forbidden"></i>'.html_safe %></p>
      <p><strong><%= t('activerecord.attributes.property.smoking') %>:</strong></p>
      <p class="text-center"><%= @property.smoking ? '<i class="fa-solid fa-smoking permited"></i>'.html_safe : '<i class="fa-solid fa-ban forbidden"></i>'.html_safe %></p>
      <p><strong><%= t('activerecord.attributes.property.wifi') %>:</strong></p>
      <p class="text-center"><%= @property.wifi ? '<i class="fa-solid fa-wifi permited"></i>'.html_safe : '<i class="fa-solid fa-ban forbidden"></i>'.html_safe %></p>
      <p><strong><%= t('activerecord.attributes.property.property_type') %>:</strong></p>
      <p class="text-center"><%= t("activerecord.attributes.property.property_types.#{@property.property_type}") %></p>
    </div>

    <% unless @property.user == current_user %>
      <h3 class="text-center my-2"><%= t('titles.booking.create') %></h3>
      <%= simple_form_for [@property, @booking] do |f| %>
        <%= f.input :date_range, as: :string, input_html: { data: {
                                                            controller: "flatpickr",
                                                            flatpickr_date_format: "d/m/Y",
                                                            flatpickr_min_date: Time.zone.now,
                                                            flatpickr_disable: @disabled_dates,
                                                            flatpickr_mode: 'range'
                                                          } } %>
        <%# <%= f.input :end_date, as: :string, input_html: { data: {
                                                            controller: "flatpickr",
                                                            flatpickr_date_format: "d/m/Y",
                                                            flatpickr_min_date: Time.zone.now,
                                                            flatpickr_disable: @disabled_dates,
                                                            flatpickr_mode: 'range'
                                                          } } %>

        <div class="form-actions text-center">
          <%= f.submit t('helpers.submit.booking.create')  %>
        </div>
      <% end %>
    <% end %>

    <div>
      <%= link_to t('buttons.back'), properties_path, class: 'btn btn-home-add' %>
    </div>
    <div>
      <%= link_to t('buttons.users.profile'), user_path(@property.user), class: 'btn btn-home-add' %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "cat_icon.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <% if current_user.photo.attached? %>
                <%= cl_image_tag current_user.photo.key, class: "avatar", alt: "dropdown menu" %>
              <% else %>
                <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
              <% end %>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to t('navbar.links.add_property'), new_property_path, class: "dropdown-item" %>
              <%= link_to t('navbar.links.list_properties'), properties_path, class: "dropdown-item" %>
              <%= link_to t('navbar.links.my_bookings'), bookings_path, class: "dropdown-item" %>
              <% if current_user.landlord? %>
                <%= link_to t('navbar.links.my_properties'), my_properties_path, class: "dropdown-item" %>
              <% end %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h1><%= @user.first_name %></h1>

<p><%= @user.about %></p>
<p><%= @user.properties.count %></p>